name: Build for Windows
description: 'Build V8 for Windows'

inputs:
  archive-name:
    description: 'Base name of the archive to create'
    default: v8_Windows
    required: false
    type: string

runs:
  using: "composite"
  steps:
    - name: Restore SCCache
      uses: actions/cache@v3
      with:
        path: .sccache
        key: ${{ runner.os }}:libv8:sccache:${{ github.run_number }}
        restore-keys: |
          ${{ runner.os }}:libv8:sccache:

    - name: Setup Scoop
      uses: MinoruSekine/setup-scoop@main

    - name: Setup SCCache
      shell: cmd
      run: |
        scoop install sccache

        set "sccacheDir=%GITHUB_WORKSPACE%\.sccache"
        if not exist "%sccacheDir%" (
          mkdir "%sccacheDir%"
        )

        echo SCCACHE_DIR="%sccacheDir%" >> %GITHUB_ENV%

    - name: Download V8 Source
      shell: cmd
      run: .\v8_download.bat

    - name: Compile V8
      shell: cmd
      run: .\v8_compile.bat

    - name: Show SCCache Status
      shell: pwsh
      run: sccache --show-stats

    - name: Setup Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1

    - name: Test V8
      continue-on-error: true
      shell: cmd
      run: .\v8_test.bat

    - name: Archive V8
      shell: pwsh
      run: .\archive.bat ${{ inputs.archive-name }}
