name: V8 Build Test

on:
  push:
    branches:
      - master
    paths-ignore:
      - "depot_tools"
      - ".gitignore"
      - ".gitpod*"

jobs:
  build-mac:
    name: Build for macOS
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Restore V8 Cache
        uses: actions/cache@v3
        with:
          path: |
            v8
            .gclient_entries
            .gclient_previous_sync_commits
            .cipd
          key: ${{ runner.os }}:libv8:v8:${{ hashFiles('**/VERSION') }}

      - name: Restore CCache
        uses: actions/cache@v3
        with:
          path: ~/Library/Caches/ccache
          key: ${{ runner.os }}:libv8:ccache:${{ github.run_number }}
          restore-keys: |
            ${{ runner.os }}:libv8:ccache:

      - name: Setup CCache for macOS
        run: |
          brew install ccache
          echo "CCACHE_CPP2=yes" >> $GITHUB_ENV
          echo "CCACHE_SLOPPINESS=time_macros" >> $GITHUB_ENV
          echo "$(brew --prefix ccache)/libexec" >> $GITHUB_PATH

      - name: Download V8 Source
        run: ./v8_download.sh

      - name: Compile V8
        run: ./v8_compile.sh

      - name: Show CCache Status
        run: ccache -s

      - name: Test V8
        continue-on-error: true
        run: ./v8_test.sh

      - name: Archive V8 Library
        uses: actions/upload-artifact@v3
        with:
          name: v8_${{ runner.os }}_amd64
          path: |
            v8/out/release/obj/libv8_monolith.a
            v8/include/
            gn-args_${{ runner.os }}.txt
          retention-days: 7

  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Restore V8 Cache
        uses: actions/cache@v3
        with:
          path: |
            v8
            .gclient_entries
            .gclient_previous_sync_commits
            .cipd
          key: ${{ runner.os }}:libv8:v8:${{ hashFiles('**/VERSION') }}

      - name: Restore CCache
        uses: actions/cache@v3
        with:
          path: ~/.ccache
          key: ${{ runner.os }}:libv8:ccache:${{ github.run_number }}
          restore-keys: |
            ${{ runner.os }}:libv8:ccache:

      - name: Setup CCache for Linux
        run: |
          sudo apt-get update && sudo apt-get install -yq ccache
          sudo update-ccache-symlinks
          echo "/usr/lib/ccache" >> $GITHUB_PATH

      - name: Download V8 Source
        run: ./v8_download.sh

      - name: Compile V8
        run: ./v8_compile.sh

      - name: Show CCache Status
        run: ccache -s

      - name: Test V8
        continue-on-error: true
        run: ./v8_test.sh

      - name: Archive V8 Library
        uses: actions/upload-artifact@v3
        with:
          name: v8_${{ runner.os }}_amd64
          path: |
            v8/out/release/obj/libv8_monolith.a
            v8/include/
            gn-args_${{ runner.os }}.txt
          retention-days: 7

  build-windows:
    name: Build for Windows
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Restore V8 Cache
        uses: actions/cache@v3
        with:
          path: |
            v8
            .gclient_entries
            .gclient_previous_sync_commits
            .cipd
          key: ${{ runner.os }}:libv8:v8:${{ hashFiles('**/VERSION') }}

      - name: Restore SCCache
        uses: actions/cache@v3
        with:
          path: C:\Users\runneradmin\AppData\Local\Mozilla\sccache
          key: ${{ runner.os }}:libv8:sccache:${{ github.run_number }}
          restore-keys: |
            ${{ runner.os }}:libv8:sccache:

      - name: Setup Scoop
        uses: ScoopInstaller/GithubActions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install SCCache
        run: scoop install sccache

      - name: Download V8 Source
        run: .\v8_download.ps1

      - name: Compile V8
        run: .\v8_compile.ps1

      - name: Show SCCache Status
        run: sccache --show-stats

      - name: Archive V8 Library
        uses: actions/upload-artifact@v3
        with:
          name: v8_${{ runner.os }}_amd64
          path: |
            v8\out\release\obj\v8_monolith.lib
            v8\include\
            gn-args_${{ runner.os }}.txt
          retention-days: 7
