name: V8 Release and Publish

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build V8
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest-large, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: true
          clean: true
          fetch-depth: 1

      - name: Build Release for Linux
        if: matrix.os == 'ubuntu-latest'
        uses: ./.github/actions/build-linux
        with:
          archive-name: v8_${{ runner.os }}_amd64

      - name: Build Release for macOS (Intel)
        if: matrix.os == 'macos-latest-large'
        uses: ./.github/actions/build-macos
        with:
          archive-name: v8_${{ runner.os }}_amd64

      - name: Build Release for macOS (Apple Silicon)
        if: matrix.os == 'macos-latest'
        uses: ./.github/actions/build-macos
        with:
          archive-name: v8_${{ runner.os }}_arm64

      - name: Build Release for Windows
        if: matrix.os == 'windows-latest'
        uses: ./.github/actions/build-windows
        with:
          archive-name: v8_${{ runner.os }}_amd64

      - name: Upload Archive
        uses: actions/upload-artifact@v4
        with:
          path: |
            *.tar.xz
            *.7z
          retention-days: 7
          overwrite: true

  release:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: build
    steps:
      - name: Download Archives
        uses: actions/download-artifact@v4

      - name: Display Downloads
        run: ls -lhR artifact

      - name: Upload Archive
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            artifact/*.tar.xz
            artifact/*.7z
