name: V8 Version Check

on:
  schedule:
    - cron: "0 1 * * *" # every day at UTC 1:00AM
  workflow_dispatch:

jobs:
  check:
    name: Check V8 Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Get Lastest Stable Version
        run: |
          current_version="$(cat VERSION)"
          latest_version="$(wget -qO- https://omahaproxy.appspot.com/all.json | \
            jq -r '.[] | select(.os == "linux") | .versions | .[] | select(.channel == "stable") | .v8_version')"

          echo "Current version: $current_version"
          echo "Latest version: $latest_version"

          if [ -n "$latest_version" ] && [ x"$latest_version" != x"$current_version" ] ; then
            echo "NEW_V8_VERSION=$latest_version" >> $GITHUB_ENV
          else
            echo "NEW_V8_VERSION=0" >> $GITHUB_ENV
          fi

      - name: Make Commit
        if: env.NEW_V8_VERSION != '0'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          echo "${{ env.NEW_V8_VERSION }}" > VERSION

          git add -f VERSION
          git commit -am "chore(v8): bump to v${{ env.NEW_V8_VERSION }}"
          git push origin master

          git tag -a "v${{ env.NEW_V8_VERSION }}" -m "v${{ env.NEW_V8_VERSION }}"
          git push --tags
